#
# This file contains the metadata for the services approved in the IO app
#
# The key for each service is the serviceId.
# All fields are optional.
#
---
#
# IO-App Team digitale
#
azure-deployc49a:
  description: |
    IO è l’applicazione sperimentale (attualmente in fase di closed beta) che permette ai cittadini
    di gestire direttamente dal proprio smartphone i rapporti con la Pubblica Amministrazione Italiana
    e l’accesso ai servizi pubblici.

    Ti invierà messaggi su come usare l'applicazione, aggiornamenti sul progetto o sulle funzionalità dell'app,
    richieste di feedback e altre istruzioni utili alla sperimentazione.

    IO è un progetto della Presidenza del Consiglio dei Ministri realizzato dal Team per la Trasformazione Digitale
    in collaborazione con Agid.

  web_url: https://io.italia.it
  email: io-testing@teamdigitale.governo.it

# TODO: this is the old admin backend service. Delete this entry once
# https://github.com/teamdigitale/digital-citizenship/pull/204 gets merged
5a563817fcc896087002ea46c49a:
  description: |
    IO è l’applicazione sperimentale (attualmente in fase di closed beta) che permette ai cittadini
    di gestire direttamente dal proprio smartphone i rapporti con la Pubblica Amministrazione Italiana
    e l’accesso ai servizi pubblici.

    Ti invierà messaggi su come usare l'applicazione, aggiornamenti sul progetto o sulle funzionalità dell'app,
    richieste di feedback e altre istruzioni utili alla sperimentazione.

    IO è un progetto della Presidenza del Consiglio dei Ministri realizzato dal Team per la Trasformazione Digitale
    in collaborazione con Agid.

  web_url: https://io.italia.it
  email: io-testing@teamdigitale.governo.it

#
# Municipality of Cagliari
#
5b4f7512a9ab400f2417f0ccc49a:
  description: |
    Il servizio della Polizia Municipale del Comune di Cagliari. Tramite IO potrai:

      * Riceve notifiche relative pagamenti necessati per sanzioni al Codice della Strada
      * Effettuare il pagamento delle sanzioni per violazioni al Codice della Strada

  tos_url: https://www.comune.cagliari.it/portale/it/note_legali.page
  privacy_url: https://www.comune.cagliari.it/portale/it/privacy.page
  web_url: https://www.comune.cagliari.it/portale/it/servizio_polizia_municipale.page
  address: Via Avicenna - 09131 Cagliari
  phone: +39 0800230606
  email: pm.ced@comune.cagliari.it
  pec: poliziamunicipale@comune.cagliari.legalmail.it

5b928ef65aaa2928c0319563c49a:
  description: |
    Il servizio della Protezione Civile del Comune di Cagliari. Tramite IO potrai:

      * Ricevere, in tempo reale, notifiche di avviso (preallarme o allarme) su criticità ambientali.

  tos_url: https://www.comune.cagliari.it/portale/it/note_legali.page
  privacy_url: https://www.comune.cagliari.it/portale/it/privacy.page
  web_url: https://servizi.comune.cagliari.it/portale/it/servizio_sms.page
  address: Via Giuseppe Mercalli, 31 - 09129 Cagliari
  phone: +39 070 6776905
  email: protezione.civile@comune.cagliari.it
  pec: protocollogenerale@comune.cagliari.legalmail.it

5b87a75d34234f1170e79deec49a:
  description: |
    Il servizio sulla Viabilità del Comune di Cagliari. Tramite IO potrai:

      * Essere avvisato in tempi utili sulla scadenza del tuo permesso ZTL
      * Richiedere e pagare (se necessario) il tuo nuovo permesso ZTL

  tos_url: https://www.comune.cagliari.it/portale/it/note_legali.page
  privacy_url: https://www.comune.cagliari.it/portale/it/privacy.page
  web_url: https://servizi.comune.cagliari.it/portale/it/richiesta_rinn_pass_ztl.page
  address: Piazza A. De Gasperi, 2 - 09125 Cagliari
  phone: +39 070 6778303
  email: ufficioztl@comune.cagliari.it
  pec: protocollogenerale@comune.cagliari.legalmail.it

#
# Demo services.
#
01CT1SFF37VFZDNFWG2SRH6RDN:
  description: |
    IO è l’applicazione sperimentale (attualmente in fase di closed beta) che permette ai cittadini di gestire
    direttamente dal proprio smartphone i rapporti con la Pubblica Amministrazione Italiana e l’accesso ai servizi pubblici.
    Ti invierà messaggi su come usare l'applicazione, aggiornamenti sul progetto o sulle funzionalità dell'app,
    richieste di feedback e altre istruzioni utili alla sperimentazione.

  web_url: https://io.italia.it
  email: io-testing@teamdigitale.governo.it

#
# Automobile Club d'Italia
#
01DBJNFSJYB53TP0AZNA8FQGJJ:
  description: |
    L'Automobile Club Italia partecipa alla closed-beta di IO. 
    Tramite IO potrai:

    * ricevere messaggi informativi a carattere istituzionale che ti accompagnano nel corso della beta;
    * essere sempre aggiornato in caso di integrazione di nuovi servizi.

  privacy_url: https://io.italia.it/ente/aci


01DBJNW5NR2M2VQTM7VG0SGNNZ:
  description: |
    I servizi relativi al Bollo Auto offerti dall'ACI permettono di calcolare e pagare le proprie tasse automobilistiche. 
    Tramite IO potrai:

    * ricevere un promemoria in prossimità della scadenza del pagamento del Bollo Auto;
    * pagare il Bollo Auto e ricevere una conferma del pagamento avvenuto.

  privacy_url: http://www.aci.it/informativa-resa-ai-sensi-dellart-13-del-regolamento-ue-2016679-gdpr.html
  web_url: https://bollo.aci.it/#/main/home
  address: ACI - Sede Legale - Via Marsala 8, 00185 Roma
  phone: 06 4998 2721
  mail: serviziogestionetasseautomobilistiche@aci.it
  pec: serviziogestionetasseautomobilistiche@pec.aci.it


01DBJNYDCT0Q5G0D0K7RFS2R2F:
  description: |
    Il servizio di gestione PRA dell'ACI si occupa della gestione del Pubblico Registro Automobilistico. Tramite IO potrai: 
    Tramite IO potrai:

    * ricevere una notifica relativa al certificato di proprietà digitale disponibile per un nuovo veicolo;
    * ricevere un riepilogo dei tuoi certificati di proprietà digitali.

  privacy_url: http://www.aci.it/informativa-resa-ai-sensi-dellart-13-del-regolamento-ue-2016679-gdpr.html
  web_url: https://iservizi.aci.it/consultacdpd/
  address: ACI - Sede Legale - Via Marsala 8, 00185 Roma
  phone: 06 4998 2715
  mail: servizio.gestione.pra@aci.it
  pec: serviziogestionepra@pec.aci.it

#
# Municipality of Milan
#
01D723T8K5SWNTV3YQF34KPJDY:
  description: |
    Il Comune di Milano partecipa alla closed-beta di IO.
    Tramite IO potrai:

    * Ricevere messaggi informativi a carattere istituzionale che ti accompagnano nel corso della beta
    * Essere sempre aggiornato in caso di integrazione di nuovi servizi

  privacy_url: http://www.comune.milano.it/wps/portal/ist/it/extra/others/footer/privacy
  phone: +39 02 02 02

01D5RQM2NVWM2QVZPQQ4FC8Z2E:
  description: |
    Lo sportello dei Servizi al Cittadino si occupa di certificati, carte d'identità e certificazioni.
    Tramite IO potrai:

    * Ricevere un promemoria in prossimità della scadenza della tua carta d'identità
    * Ricevere un riepilogo dei tuoi dati anagrafici
    * Ricevere un promemoria in prossimità della scadenza dei tuoi pass per la mobilità

  privacy_url: http://www.comune.milano.it/wps/portal/ist/it/extra/others/footer/privacy
  web_url: https://login.comune.milano.it/pkmsvouchfor?milano&https://www.comune.milano.it/wps/myportal/myMilano/app/fascicolocittadino
  phone: +39 02 884 62274
  pec: servizialcittadino@postcert.comune.milano.it

01D5ECFA96C6HYNPXVC6P55D1S:
  description: |
    Servizio Area B del Comune di Milano.
    Tramite IO potrai:

    * Ricevere una notifica al primo passaggio di un veicolo non autorizzato in area B

  privacy_url: http://www.comune.milano.it/wps/portal/ist/it/extra/others/footer/privacy
  web_url: http://www.comune.milano.it/wps/portal/ist/it/servizi/mobilita/Area_B/area_b
  phone: +39 020202
  pec: mtaareab@postacert.comune.milano.it

01D721ZVRSXW793EK43HTAQM05:
  description: |
    Il servizio Procedure Sanzionatorie e Traffico del Comune di Milano si occupa delle sanzioni al codice della strada e della riscossione dell'importo dovuto.
    Tramite IO potrai:

    * Ricevere avvisi di pagamento in caso di emissione di un verbale e procedere al pagamento

  privacy_url: http://www.comune.milano.it/wps/portal/ist/it/extra/others/footer/privacy
  web_url: https://www.comune.milano.it/wps/myportal/ist/it/servizi/servizionline/pagine_servizi/multe_sa/Multe
  address: Sportello Unico Polizia Locale - Area Procedure Sanzionatorie e Traffico - Via Friuli n° 30
  phone: +39 02 772 73143
  email: PL.SanzioniVerbali@comune.milano.it

01D7228TKGP7F3BGVQG88PXTH6:
  description: |
    Lo sportello di Monitoraggio e Riscossione Servizi Educativi si occupa della gestione del pagamento dei contributi d'iscrizione.
    Tramite IO potrai:

    * Ricevere un riepilogo delle rette scolastiche pagate

  web_url: https://login.comune.milano.it/pkmsvouchfor?milano&https://www.comune.milano.it/wps/myportal/myMilano/app/fascicolocittadino
  phone: +39 02 884 62688
  email: Ed.ServEducativiRette@comune.milano.it

01D722SKRRFMGA3FZ8NWQ4F643:
  description: |
    Lo sportello unico per l'edilizia fornisce informazioni e gestisce pratiche di protocollazione legate all'urbanistica.
    Tramite IO potrai:

    * Ricevere un promemoria in caso di appuntamento con l'ufficio Edilizia e Territorio
    * Ricevere una notifica in caso di disdetta di un appuntamento

  privacy_url: http://www.comune.milano.it/wps/portal/ist/it/extra/others/footer/privacy
  web_url: https://login.comune.milano.it/pkmsvouchfor?milano&https://www.comune.milano.it/wps/myportal/myMilano/app/fascicolocittadino
  phone: +39 02 884 66779
  email: sueurp@comune.milano.it

01D72312AZT81N4JC3GV6980CK:
  description: |
    Il servizio dei Tributi Locali del Comune di Milano gestisce il tributo sui rifiuti (TARI/TARES/TARSU).
    Tramite IO potrai:

    * Ricevere un riepilogo degli immobili per cui hai pagato la TARI
    * Ricevere un avviso di accertamento in caso di mancato pagamento delle rate passate

  privacy_url: http://www.comune.milano.it/wps/portal/ist/it/extra/others/footer/privacy
  web_url: https://login.comune.milano.it/pkmsvouchfor?milano&https://www.comune.milano.it/wps/myportal/myMilano/app/fascicolocittadino
  phone: +39 02 02 02
  pec: tassarifiuti@pec.comune.milano.it

01D723AK9TM6KHS97M4BJ1HMN0:
  description: |
    Il servizio Pass Mobilità permette di gestire i tuoi permessi per la mobilità in città.
    Tramite IO potrai:

    * Ricevere un riepilogo dei tuoi pass attivi
    * Ricevere un promemoria in prossimità della scadenza dei tuoi pass per la mobilità

  privacy_url: https://www.muoversi.milano.it/web/portale-mobilita/privacy
  web_url: http://www.comune.milano.it/passonline
  phone: +39 02 02 02
  pec: servizialcittadino@postcert.comune.milano.it

#
# Municipality of Palermo
#
01CTY5EYNZMT8GEW50EC57JB24:
  description: |
    Comunicazioni e servizi del Comune di Palermo.
    Tramite IO potrai ricevere messaggi e comunicazioni dai seguenti dipartimenti:

      * Polizia Municipale;
      * Mobilità Urbana;
      * Tributi;
      * Ambiente e Protezione Civile;
      * Sussidi Economici;
      * Servizi Scolastici.

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  web_url: https://comune.palermo.it/
  email: io-testing@teamdigitale.governo.it

01CT1WHDPJWNPJRKQ1X8F95P2K:
  description: |
    Il servizio della Polizia Municipale del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere notifiche relative pagamenti necessati per sanzioni al Codice della Strada
      * Effettuare il pagamento delle sanzioni per violazioni al Codice della Strada

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  web_url: https://servizionline.comune.palermo.it/portcitt/jsp/home.jsp?modo=info&info=servizi.jsp&ARECOD=40&S=30
  phone: 0916954211
  email: io-testing@teamdigitale.governo.it
  address: Via Dogali n.29
  pec: comandopoliziamunicipale@cert.comune.palermo.it

01CT1WHSHWAGRF8SMYS6CSR5FS:
  description: |
    Il servizio sulla Mobilità Urbana del Comune di Palermo.
    Tramite IO potrai:

      * Essere avvisato in tempi utili sulla scadenza del tuo permesso ZTL
      * Richiedere e pagare (se necessario) il tuo nuovo permesso ZTL

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  web_url: https://ztl.comune.palermo.it/ztl/jsp/home.do?sportello=ztl
  phone: 0917401606
  email: io-testing@teamdigitale.governo.it
  address: Via Ausonia n.69
  pec: mobilitaurbana@cert.comune.palermo.it
  app_ios: https://itunes.apple.com/it/app/ztl-palermo/id1166868545?mt=8
  app_android: https://play.google.com/store/apps/details?id=it.korec.palermomobilita

01CT1WJ8D0AVSRV9N7S2NM2JBF:
  description: |
    Il servizio dei Tributi del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere notifiche quando un nuovo documento viene inserito nel tuo Cassetto Tributi

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  web_url: https://servizionline.comune.palermo.it/portcitt/jsp/home.jsp?modo=info&info=servizi.jsp&ARECOD=10&S=40
  phone: 091 7404508; 091 7404501
  address: Piazza G. Cesare n.6
  email: io-testing@teamdigitale.governo.it
  pec: settoretributi@cert.comune.palermo.it

01CT1WJKVB6M0SDNXHJHJJBDX9:
  description: |
    Il servizio dei Tributi del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere notifiche, in data utile, sulla data/ora degli appuntamenti presso l'Ufficio Tributi e inserire un promemoria nel calendario
      * Ricevere notifiche in caso di eventuali disdette da parte dell’Ufficio

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  web_url: https://servizionline.comune.palermo.it/portcitt/jsp/home.jsp?modo=info&info=servizi.jsp&ARECOD=10&SERCOD=1084&sportello=portcitt
  phone: 091 7404508; 091 7404501
  address: Piazza G. Cesare n.6
  email: io-testing@teamdigitale.governo.it
  pec: settoretributi@cert.comune.palermo.it

01CT1WK81HJA0KGENDPEPXCJXJ:
  description: |
    Il servizio della Protezione Civile del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere, in tempo reale, notifiche di avviso (preallarme o allarme) su criticità ambientali

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  email: io-testing@teamdigitale.governo.it

01CT1WM5VX706MDQ0DM4ZVAGAG:
  description: |
    Il servizio di sussidio economico ai cittadini del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere notifiche quando il sussidio economico ti è stato accreditato sul conto

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  email: io-testing@teamdigitale.governo.it

01CT1WMH651JE5DGP7RX9MKV6G:
  description: |
    Il servizio Scolastico del Comune di Palermo.
    Tramite IO potrai:

      * Ricevere notifiche su comunicazioni relative all'apertura delle iscrizioni al nido di infanzia, mensa e trasporti
      * Ricevere notifiche e pagare le rette scolastiche, delle mense e dei trasporti.

  tos_url: https://www.comune.palermo.it/info.php
  privacy_url: https://www.comune.palermo.it/privacy.php
  email: io-testing@teamdigitale.governo.it

#
# Municipality of Turin
#
01D4AQHBKESFSX98TK52PMD5S3:
  description: |
    Il servizio di prenotazioni di appuntamento presso gli sportelli del Comune di Torino.
    Tramite IO potrai:

      * Ricevere notifiche sulla data/ora degli appuntamenti presso gli sportelli del Comune di Torino

  tos_url: http://www.comune.torino.it/condizioni.shtml
  privacy_url: http://www.comune.torino.it/condizioni.shtml#privacy
  email: io-testing@teamdigitale.governo.it

01D4AQHCWWH2366GDBHV6MXDVT:
  description: |
    Il servizio di Iscrizione ai Nidi d'infanzia del Comune di Torino.
    Tramite IO potrai:

      * Ricevere notifiche su comunicazioni relative alle iscrizioni ai nidi d'infanzia del Comune di Torino

  tos_url: http://www.comune.torino.it/nidi
  privacy_url: http://www.comune.torino.it/nidi
  email: io-testing@teamdigitale.governo.it
